# this was autogenerated by: "virkshop/plugins/python.deno.js"
;
# all its doing is importing that javascript^, running a specific function from it, and then shell-sourcing the string output
;
'/home/jeffhykin/.deno/1.40.3/bin/deno' 'eval' '-q' '
                                                    import { FileSystem } from "https://deno.land/x/quickr@0.6.64/main/file_system.js"
                                                    const [ virkshopFile, tempShellOutputPath, pluginPath ] = Deno.args
                                                    const { virkshop, shellApi } = await import(virkshopFile)
                                                    const { pluginOutput } = await virkshop._internal.importPlugin(pluginPath)
                                                    const result = await pluginOutput.events["@setup_with_system_tools/054_000_setup_python_venv"].apply(pluginOutput)
                                                    const shellString = shellApi.joinStatements((result||[]))
                                                    await FileSystem.write({
                                                        data: shellString,
                                                        path: tempShellOutputPath,
                                                    })
                                                ' '--' '/home/jeffhykin/repos/valve_car_tracker_2/virkshop/support/virkshop.js' '/home/jeffhykin/repos/valve_car_tracker_2/virkshop/temporary.ignore/short_term/event_evals/06614541656161139.sh' 'python.deno.js'
;
'.' '/home/jeffhykin/repos/valve_car_tracker_2/virkshop/temporary.ignore/short_term/event_evals/06614541656161139.sh'