#!/usr/bin/env -S '/Users/jeffhykin/.deno/bin/deno' run --allow-all
// NOTE: this file was auto-generated by: "virkshop/plugins/python.deno.js"
//       edit that file, not this one!
import { virkshop } from "../support/virkshop.js"
const {pluginOutput} = await virkshop._internal.importPlugin("python.deno.js")
await pluginOutput.events["clean/054_000_python_venv"].apply(pluginOutput, ...Deno.args)