language: c

env:
   global:
     - VERBOSE: 1

os: linux
dist: xenial

jobs:
   include:
     - os: linux
       env: USE_ASAN=ON CONFIG=Release USE_SINGLE_PRECISION=On RELEASE_FILE_SUFFIX=".f"
     - os: linux
       env: USE_ASAN=ON CONFIG=Debug USE_SINGLE_PRECISION=Off
     - os: linux
       env: USE_ASAN=OFF CONFIG=Release USE_SINGLE_PRECISION=Off
     - os: windows
       env: CONFIG=Release CMAKE_GENERATOR_PLATFORM=x64 CMAKE_GENERATOR="Visual Studio 15 2017" VERBOSE=1 USE_SINGLE_PRECISION=Off

install:
  - ./useful_files/travis/$TRAVIS_OS_NAME.install.sh

script:
   - ./useful_files/travis/$TRAVIS_OS_NAME.sh

before_deploy:
  - ./useful_files/travis/$TRAVIS_OS_NAME.before_deploy.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - libsurvive-$TRAVIS_TAG-$TRAVIS_OS_NAME-$CONFIG$RELEASE_FILE_SUFFIX.zip
      - dist/*.whl
    skip_cleanup: true
    on:
      branch: master
      condition: $CONFIG=Release
      tags: true
    