virkshop:
    projectLinks:
        # FIXME
        # # comment-in these to allow them to auto-link virkshop stuff into the project folder
        # !path/relative_to_project ./commands: !path/relative_to_virkshop ./commands
    
    debuggingLevel: 1
    fileExtensionsToIgnore:
        - .ignore
        - .keep