#!/usr/bin/env -S '/Users/jeffhykin/.deno/1.40.3/bin/deno' run --allow-all
// NOTE: this file was auto-generated by: "virkshop/plugins/python.deno.js"
//       edit that file, not this one!
import { virkshop } from "../support/virkshop.js"
const {pluginOutput} = await virkshop._internal.importPlugin("python.deno.js")
await pluginOutput.events["git/post-update/054_000_python_venv"].apply(pluginOutput, ...Deno.args)